namespaces:
  adms: http://www.w3.org/ns/adms#
  cv: http://data.europa.eu/m8g/
  dct: http://purl.org/dc/terms/
  locn: http://www.w3.org/ns/locn#
  person: http://www.w3.org/ns/person#
  shacl: http://www.w3.org/ns/shacl#
input:
  file: core-person-ap.ttl
  format: ttl
  shapestart: "#"
  shapeend: "Shape"
output:
  file: core-person.xlsx
  classuri: "Class URI"
  prefix: "PREFIX"
  rdftype: "rdf:type"
  rdfclass: "rdfs:Class"
  line:
    bgcolor: "#EBF1DE"
    URI: "URI"
    type: "rdf:type"
    datatypes:
      langString: 
        namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString"
        suffix: "@en"